print("|itszw--------------Ufo------Fe--------------itszw#2241---------------------")
print("|                 Script Yuklendi                                         --")
print("|FE UFO script made by itszw#2241 // script itszw#2241 Tarafindan Yapim --")
print("|required hat // istenen hat: roblox.com/catalog/8151404994 --")
print("|--------------Kontroller // Controls--------------")
print("|T - toggle stand-by mode // Bekleme Modu")
print("|    G - gun mode, doesnt really do anything // Silah Modu Client Side")
print("|    B - toggle control mode // Uzaktan Kontrol Etme")
print("|-------------Ufo Kontrolleri // UFO controls----------")
print("|    WASD - move around // WASD - Etrafta Gezinmeni Sağlar")
print("|    QE - rotate left/right // Q Ve E - Sağ Sola Donmeni Sağlar")
print("|    FC - go up/down // F Ve C Yukarı Aşşağı Yapar")
print("-----------------------Discord------------------------------------")
print("---------------------itszw#2241-----------------------------------")